apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
   - name: web
     image: nginx
     livenessProbe:
       httpGet:
         path: /
         port: 80
       initialDelaySeconds: 5     
       periodSeconds: 10      
