apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: nginx-redis-pod
spec:
  containers:
    - image: nginx:latest
      name: nginx-container
      ports:
       - containerPort: 80  
    - image: redis
      name: redis-container
      ports:
       - containerPort: 6379  
