apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-pod-new
spec:
  containers:
    - name: nginx
      image: nginx
      ports:  
       - containerPort: 80
  restartPolicy: Always
