apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
 containers:
   - name: web
     image: nginx
     readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5 
      periodSeconds: 5     
