apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-server-rs
spec:
  replicas: 4
  selector:
    matchLabels: 
      name: httpd-pod
  template:
    metadata:
      labels:
        name: httpd-pod
    spec:    
      containers:
        - name: httpd-server-container
          image: httpd
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80