apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-pod
  template:
    metadata:
      labels:  
         name: redis-pod
    spec:
      containers:
        - name: redis-container
          image: redis      
