apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
  labels:
    run: resource-pod
spec:
  containers:
  - name: resource-pod
    image: redis
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
